SELECT getdate() as Todaydate
SELECT GETDATE() + 365
SELECT CONVERT(varchar,GETDATE())
SELECT CONVERT(varchar,GETDATE(),106)
SELECT CONVERT(varchar,GETDATE())
SELECT DATEDIFF(Month,'31-dec-08','31-mar-09')
SELECT DATEDIFF(YEAR,'25-jan-12','14-sep-10')
SELECT DATEDIFF(HOUR,'25-jan-12 7:00','26-jan-12 10:30') 
SELECT DAY('12/05/2016'),MONTH('2016-05-12'),YEAR('2016/05/12')
SELECT DATEADD(YEAR,5,GETDATE())
SELECT DATEADD(MONTH,-2,GETDATE())
SELECT DATENAME(MONTH,GETDATE()),DATEPART(MONTH,GETDATE())
SELECT EOMONTH(GETDATE())
SELECT DATEADD(DAY,30,GETDATE ())
SELECT DATEDIFF(YEAR,'2004-01-22',GETDATE())
SELECT DATEDIFF(MONTH,'2004-01-22',GETDATE())


CREATE TABLE Student_Marks(
	Sid int not null,
	SName varchar(50) not null,
	Marks int not null
)
Insert Into Student_Marks Values (1,'John',90),(2,'Martin',80),(3,'Carol',89),(4,'Jack',99),(5,'Rose',88),(6,'Mary',90)
SELECT *FROM Student_Marks
SELECT COUNT(Sid) FROM Student_Marks
SELECT SUM(Marks) FROM Student_Marks
SELECT AVG(Marks) FROM Student_Marks
SELECT MIN(Marks) FROM Student_Marks
SELECT MAX(Marks) FROM Student_Marks
