CREATE TABLE EMPLOYEE(
	EID int not null,
	EName varchar(50) not null,
	Department varchar(50) not null,
	Salary Decimal(8,2) not null,
	JoiningDate datetime not null,
	City varchar(50) not null
)

INSERT INTO Employee VALUES(101,'Rahul','Admin',56000,'1-Jan-90','Rajkot')
,(102,'Hardik','IT',18000,'25-sep-90','Ahmedabad')
,(103,'Bhavin','HR',25000,'14-may-91','Baroda')
,(104,'Bhoomi','Admin',39000,'8-Feb-91','Rajkot')
,(105,'Rohit','IT',17000,'23-Jul-90','Jamnagar')
,(106,'Priya','IT',9000,'18-Jan-90','Ahmedabad')
,(107,'Neha','HR',34000,'25-dec-91','Rajkot')



SELECT MAX(SALARY) as Maximum,MIN(SALARY) as Minimum ,AVG(SALARY) as Average_Sal FROM EMPLOYEE
SELECT COUNT(*) as TotalEMPLOYEE FROM EMPLOYEE
SELECT MAX(SALARY) FROM EMPLOYEE WHERE Department='IT'
SELECT COUNT(DISTINCT City) as Unq_CIty FROM EMPLOYEE
SELECT CITY,COUNT(EName) FROM EMPLOYEE GROUP BY City
SELECT CITY ,COUNT(EID) AS TOTAL_EMPLOYEE FROM EMPLOYEE GROUP BY CITY HAVING COUNT(EID)>1
SELECT DEPARTMENT , SUM(Salary) AS [Total Salary] FROM EMPLOYEE GROUP BY Department
SELECT AVG(SALARY) [AVG-SAL] FROM EMPLOYEE GROUP BY DEPARTMENT
SELECT MIN(SALARY) [Min_Sal] FROM EMPLOYEE WHERE CITY='AHMEDABAD'
SELECT Department FROM  EMPLOYEE WHERE CITY='RAJKOT' GROUP BY Department HAVING SUM(SALARY)>50000
SELECT COUNT(Ename) AS TOTAL_EMP FROM EMPLOYEE WHERE CITY='RAJKOT'
SELECT MAX(SALARY)-MIN(SALARY) AS SAL_DIFFRRENCE FROM EMPLOYEE
SELECT COUNT(*) FROM EMPLOYEE WHERE JoiningDate<'1991-01-01'
SELECT Department,SUM(SALARY)AS TOTAL_SAL FROM EMPLOYEE GROUP BY Department HAVING SUM(SALARY)>35000 ORDER BY SUM(SALARY)
SELECT DEPARTMENT,COUNT(*) FROM EMPLOYEE GROUP BY DEPARTMENT HAVING COUNT(ENAME)>2
 SELECT MIN(SALARY) AS MIN_SAL FROM EMPLOYEE WHERE CITY='RAJKOT'	
SELECT City,COUNT(EName) FROM EMPLOYEE GROUP BY City
SELECT DEPARTMENT,MIN(Salary) FROM EMPLOYEE GROUP BY Department 
SELECT SUM(SALARY) FROM EMPLOYEE GROUP BY CITY
SELECT DEPARTMENT,MIN(SALARY),MAX(SALARY),SUM(SALARY) FROM EMPLOYEE GROUP BY Department

